name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: ⬇️ Checkout Code
          uses: actions/checkout@v4

        - name: 🐢 Setup Node
          uses: actions/setup-node@v4
          with:
            node-version: '22'
            cache: npm

        - name: 🏗️ Install Dependencies
          run: npm install

        - name: 🧪 Test
          env:
            BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
            BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
          run: npx wdio config/wdio.ios.conf.ts --spec test/specs/ios/ios-todo-item-screen.spec.ts

        - name: 📦 Upload Logs
          uses: actions/upload-artifact@v4
          if: failure()
          with:
            name: logs
            path: logs
